apiVersion: v1
kind: Service
metadata:
  name: {{ include "e2sim-helm.fullname" . }}
  labels:
    {{- include "e2sim-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: simulator
      protocol: TCP
  selector:
    {{- include "e2sim-helm.selectorLabels" . | nindent 4 }}
