apiVersion: v1
kind: ConfigMap
metadata:
  name: envman-configmap
data:
  application.yaml: |-
    ues:
      quantity: 256

    antennae:
      # Original four gNB
      - name: "E2node1"
        gnb_id: 1
        endpoint: "http://e2node1-e2sim-helm-simulator.ricplt:8081/v1"
        location: [47.0, 47.0, 25.0]
        numerology: 4
        frequency: 7175    # MHz
        power: 1          # W
        gain: 8
        bandwidth: 100    # MHz

      - name: "E2node2"
        gnb_id: 2
        endpoint: "http://e2node2-e2sim-helm-simulator.ricplt:8081/v1"
        location: [47.0, 87.0, 25.0]
        numerology: 4
        frequency: 7275
        power: 1          # W
        gain: 8
        bandwidth: 100    # MHz

      - name: "E2node3"
        gnb_id: 3
        endpoint: "http://e2node3-e2sim-helm-simulator.ricplt:8081/v1"
        location: [47.0, 127.0, 25.0]
        numerology: 4
        frequency: 7375
        power: 1          # W
        gain: 8
        bandwidth: 100    # MHz

      - name: "E2node4"
        gnb_id: 4
        endpoint: "http://e2node4-e2sim-helm-simulator.ricplt:8081/v1"
        location: [157.0, 47.0, 25.0]
        numerology: 4
        frequency: 7475
        power: 1          # W
        gain: 8
        bandwidth: 100    # MHz

      # Additional gNBs up to 25; the pattern below systematically increments
      # location and frequency, but you can adjust as needed.

      - name: "E2node5"
        gnb_id: 5
        endpoint: "http://e2node5-e2sim-helm-simulator.ricplt:8081/v1"
        location: [157.0, 87.0, 25.0]    # example
        numerology: 4
        frequency: 7575
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node6"
        gnb_id: 6
        endpoint: "http://e2node6-e2sim-helm-simulator.ricplt:8081/v1"
        location: [157.0, 127.0, 25.0]
        numerology: 4
        frequency: 7675
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node7"
        gnb_id: 7
        endpoint: "http://e2node7-e2sim-helm-simulator.ricplt:8081/v1"
        location: [157.0, 167.0, 25.0]
        numerology: 4
        frequency: 7775
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node8"
        gnb_id: 8
        endpoint: "http://e2node8-e2sim-helm-simulator.ricplt:8081/v1"
        location: [157.0, 207.0, 25.0]
        numerology: 4
        frequency: 7875
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node9"
        gnb_id: 9
        endpoint: "http://e2node9-e2sim-helm-simulator.ricplt:8081/v1"
        location: [157.0, 247.0, 25.0]
        numerology: 4
        frequency: 7975
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node10"
        gnb_id: 10
        endpoint: "http://e2node10-e2sim-helm-simulator.ricplt:8081/v1"
        location: [197.0, 47.0, 25.0]
        numerology: 4
        frequency: 8075
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node11"
        gnb_id: 11
        endpoint: "http://e2node11-e2sim-helm-simulator.ricplt:8081/v1"
        location: [197.0, 87.0, 25.0]
        numerology: 4
        frequency: 8175
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node12"
        gnb_id: 12
        endpoint: "http://e2node12-e2sim-helm-simulator.ricplt:8081/v1"
        location: [197.0, 127.0, 25.0]
        numerology: 4
        frequency: 8275
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node13"
        gnb_id: 13
        endpoint: "http://e2node13-e2sim-helm-simulator.ricplt:8081/v1"
        location: [197.0, 167.0, 25.0]
        numerology: 4
        frequency: 8375
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node14"
        gnb_id: 14
        endpoint: "http://e2node14-e2sim-helm-simulator.ricplt:8081/v1"
        location: [197.0, 207.0, 25.0]
        numerology: 4
        frequency: 8475
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node15"
        gnb_id: 15
        endpoint: "http://e2node15-e2sim-helm-simulator.ricplt:8081/v1"
        location: [237.0, 47.0, 25.0]
        numerology: 4
        frequency: 8575
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node16"
        gnb_id: 16
        endpoint: "http://e2node16-e2sim-helm-simulator.ricplt:8081/v1"
        location: [237.0, 87.0, 25.0]
        numerology: 4
        frequency: 8675
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node17"
        gnb_id: 17
        endpoint: "http://e2node17-e2sim-helm-simulator.ricplt:8081/v1"
        location: [237.0, 127.0, 25.0]
        numerology: 4
        frequency: 8775
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node18"
        gnb_id: 18
        endpoint: "http://e2node18-e2sim-helm-simulator.ricplt:8081/v1"
        location: [237.0, 167.0, 25.0]
        numerology: 4
        frequency: 8875
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node19"
        gnb_id: 19
        endpoint: "http://e2node19-e2sim-helm-simulator.ricplt:8081/v1"
        location: [237.0, 207.0, 25.0]
        numerology: 4
        frequency: 8975
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node20"
        gnb_id: 20
        endpoint: "http://e2node20-e2sim-helm-simulator.ricplt:8081/v1"
        location: [277.0, 47.0, 25.0]
        numerology: 4
        frequency: 9075
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node21"
        gnb_id: 21
        endpoint: "http://e2node21-e2sim-helm-simulator.ricplt:8081/v1"
        location: [277.0, 87.0, 25.0]
        numerology: 4
        frequency: 9175
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node22"
        gnb_id: 22
        endpoint: "http://e2node22-e2sim-helm-simulator.ricplt:8081/v1"
        location: [277.0, 127.0, 25.0]
        numerology: 4
        frequency: 9275
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node23"
        gnb_id: 23
        endpoint: "http://e2node23-e2sim-helm-simulator.ricplt:8081/v1"
        location: [277.0, 167.0, 25.0]
        numerology: 4
        frequency: 9375
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node24"
        gnb_id: 24
        endpoint: "http://e2node24-e2sim-helm-simulator.ricplt:8081/v1"
        location: [277.0, 207.0, 25.0]
        numerology: 4
        frequency: 9475
        power: 1
        gain: 8
        bandwidth: 100

      - name: "E2node25"
        gnb_id: 25
        endpoint: "http://e2node25-e2sim-helm-simulator.ricplt:8081/v1"
        location: [317.0, 47.0, 25.0]
        numerology: 4
        frequency: 9575
        power: 1
        gain: 8
        bandwidth: 100