
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-envman
data:
  application.yaml: |-
    ues: 
      quantity: 10

    antennae:
      - name: "E2node1"
        gnb_id: 1
        endpoint: "http://e2node1-e2sim-helm-simulator.ricplt:8081/v1"
        location: [47.0, 47.0, 25.0]
        numerology: 4
        frequency: 7175 # MHz
        power: 10 # W
        gain: 8
        bandwidth: 100 # MHz

      - name: "E2node2"
        gnb_id: 2
        endpoint: "http://e2node2-e2sim-helm-simulator.ricplt:8081/v1"
        location: [47.0, 87.0, 25.0]
        numerology: 4
        frequency: 7275
        power: 10 # W
        gain: 8
        bandwidth: 100 # MHz

      - name: "E2node3"
        gnb_id: 3
        endpoint: "http://e2node3-e2sim-helm-simulator.ricplt:8081/v1"
        location: [47.0, 127.0, 25.0]
        numerology: 4
        frequency: 7375
        power: 10 # W
        gain: 8
        bandwidth: 100 # MHz

      - name: "E2node4"
        gnb_id: 4
        endpoint: "http://e2node4-e2sim-helm-simulator.ricplt:8081/v1"
        location: [157.0, 47.0, 25.0]
        numerology: 4
        frequency: 7475
        power: 10 # W
        gain: 8
        bandwidth: 100 # MHz

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envman-sbrc-24-deployment
spec:
  replicas: 1 # Specify the number of pods to run
  selector:
    matchLabels:
      app: environment-manager
  template:
    metadata:
      labels:
        app: environment-manager
    spec:
      hostname: envman-sbrc-24
      volumes:
        - name: configmap-volume
          configMap:
            name: configmap-envman
      containers:
        - name: environment-manager
          image: docker.io/trbecker/sbrc-24:0.0.2
          imagePullPolicy: Always
          command: ["python3"]
          args: ["experiment.py"]
          volumeMounts:
            - name: configmap-volume
              mountPath: /etc/config/configmap
          resources:
            limits:
              cpu: "1000m"
              memory: "256Mi"