affinity: {}
fullnameOverride: ''
image:
  args:
    e2term: 10.43.0.225
    mcc: 724
    mnc: 11
    nodebid: 2
    port: 30001
  command: e2sim
  pullPolicy: IfNotPresent
  repository: zanattabruno/e2sim-rc
  tag: 'TNSM-24'
nameOverride: ''
#nodeSelector:
  #kubernetes.io/hostname: node2
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
service:
  portSimulator: 8081
  portO1: 8090
  tls: []
  type: ClusterIP
  typehandover: NodePort
tolerations: []